### ISSUE TITLE
hlmarks_stacked_signs_order does nothing

### ISSUE THREAD

**Issue by yggdr** [AT-AT/hlmarks.vim#1]
Hi,

hlmarks_stacked_signs_order seems to do nothing. No matter what I set it to, when I am on a line with an Error Mark generated by syntastic, I can set a new mark that overwrites the syntastic mark. I always want the syntastic error symbols on top, how do I do this?

Thanks

**Comment by AT-AT** [comment]
Hello, yggdr

Thanks try this plug-in!
I released minor version that fixed reported problem, please try again if you don't mind.

8-)

**Comment by yggdr** [comment]
Seems to work now, thank you :)
