### ISSUE TITLE
Flood of "E716: Ket not present"

### ISSUE THREAD

**Issue by yggdr** [AT-AT/hlmarks.vim#2]
Every 20 seconds or so (sometimes longer), I get an error message like this:

```
Error detected while processing function <SNR>128_update_signs:
line 27:
E716: Key not present in Dictionary: 26
Press ENTER or type command to continue
Error detected while processing function <SNR>128_update_signs:
line 27:                  
E15: Invalid expression: sign_spec == sign_cache[line_no]
Press ENTER or type command to continue
```

The number in `Key not present in Dictionary:` varies, and it can happen in seemingly any mode.

**Comment by AT-AT** [comment]
Thanks for reporting again! (and apologise for inconvenience..)
I could not reproduce reported problem, but add handling for it and released.
Could you try again?
And, could you tell me the operation or more detail of when reported problem occurs if it's OK with you?

**Comment by yggdr** [comment]
Well, I realised I could force the issue with syntastic. Once syntastic opens an error-list-window, I'd get these errors. But it's not limited to syntastic use.
I updated, and couldn't force the errors with syntastic anymore, so it might be resolved. I'll keep you posted should they resurface.
Thanks!

**Comment by AT-AT** [comment]
Thanks for trying update!
(..I will continue further investigation based on your report..)
8-)
